  var textArray = [
  ":3",
  "yello",
  "haii",
  "yo waddup",
  "listen to Lemon Demon",
  "listen to Tally Hall",
  "listen to glass beach",
  "fortnite",
  "eating Burger King",
  "paws",
  "definitely a cat",
  "definitely a slugcat",
  "wawa",
  "meow",
  "hungry",
  "undefined",
  "defined!",
  "porls...",
  "gadzooks!",
  "you should click that big title there ^",
  "meow",
  "bark",
  "say it ain't so!",
  "creature of secrets",
  "anybody got $12.76",
  "kinda want McDonald's",
  "'how strange it is to be anything at all'",
  "could really go for some McDonald's",
  "fat free",
  "not fat free",
  "no eta",
  "play Rain World!",
  "woah",
  "whoa",
  "like sleep like death",
  
  ];
  var randomNumber = Math.floor(Math.random() * textArray.length);
  document.getElementById("randomNumber").innerHTML = textArray[randomNumber];