window.onload = function() {
  var titles = ['the big red thing’s site', '<-- slugcat fella', 'T.W.O.A.T.', 'psst, play Rain World', 'the site'];
  var random = Math.floor(Math.random() * titles.length);
  var titleElement = document.getElementById('title')
  titleElement.innerHTML = titles[random];
}
  
  var textArray = [
  ":3",
  "yello",
  "haii",
  "yo waddup",
  "listen to Lemon Demon",
  "listen to Tally Hall",
  "listen to glass beach",
  "fortnite",
  "eating Burger King",
  "paws",
  "definitely a cat",
  "definitely a slugcat",
  "wawa",
  "meow",
  "the nail in my head is the eye of the storm",
  "hungry",
  "undefined",
  "defined!",
  "'an unimaginable gift.'",
  "'an unimaginable curse.'",
  "porls...",
  "never in the dark, never in the light",
  "gadzooks!",
  "you should click that big title there ^",
  "when you left, you left me paralyzed",
  "oh, no, no, oh, yeah",
  "meow",
  "bark",
  "it's ungrapesable",
  "over and over and never again",
  "say it ain't so!",
  "well, hello, goodbye, I'll see you in hell",
  "'this moment, right here! it is where we are meant to be.'",
  "'swim with the tide or against it.'",
  "creature of secrets",
  "love the ones with whom you fight",
  "love for want and want for more",
  "sigil signs in hexadecimal hues",
  "anybody got $12.76",
  "kinda want McDonald's",
  "I've been coming down, I've been coming down",
  "'how strange it is to be anything at all'",
  "could really go for some McDonald's",
  "keep it coming back",
  "these fishes gay. good for them, good for them.",
  "nothing ever seems happening without you",
  "alright, already, we'll all float on",
  "fat free",
  "end of the world on April Fools' day",
  "contains trans fats",
  "'the irony is not lost on me, mouse!'",
  "no eta",
  "play Rain World!",
  "woah",
  "whoa",
  "like sleep like death",
  
  ];
  var randomNumber = Math.floor(Math.random() * textArray.length);
  document.getElementById("randomNumber").innerHTML = textArray[randomNumber];